[package]
name = "ttoken-types"
authors.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
execution-core = { workspace = true }

bytecheck = { workspace = true }
rkyv = { workspace = true }
